# Generated by Django 5.2.7 on 2025-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_img', models.ImageField(blank=True, db_column='ItemImg', null=True, upload_to='items/')),
                ('item_name', models.CharField(db_column='ItemName', max_length=100)),
                ('item_desc', models.TextField(db_column='ItemDesc')),
                ('item_stack', models.CharField(blank=True, choices=[('Linear', 'Linear'), ('Exponential', 'Exponential'), ('Hyperbolic', 'Hyperbolic'), ('Reciprocal', 'Reciprocal'), ('Special', 'Special')], db_column='ItemStack', max_length=32)),
                ('item_tier', models.CharField(blank=True, choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Legendary', 'Legendary'), ('Boss', 'Boss'), ('Lunar', 'Lunar'), ('Void', 'Void'), ('Untiered', 'Untiered'), ('Equipment', 'Equipment'), ('Elite', 'Elite')], db_column='ItemTier', max_length=24)),
                ('item_act_pass', models.CharField(choices=[('Acive', 'Active'), ('Passive', 'Passive')], db_column='ItemActPass', max_length=12)),
            ],
            options={
                'db_table': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mons_img', models.ImageField(blank=True, db_column='MonsImg', null=True, upload_to='monsters/')),
                ('mons_name', models.CharField(db_column='MonsName', max_length=100)),
                ('mons_hp', models.DecimalField(db_column='MonsHP', decimal_places=2, max_digits=10)),
                ('mons_regen', models.DecimalField(db_column='MonsRegen', decimal_places=2, max_digits=10)),
                ('mons_armour', models.DecimalField(db_column='MonsArmour', decimal_places=2, max_digits=10)),
                ('mons_spd', models.DecimalField(db_column='MonsSpd', decimal_places=2, max_digits=10)),
                ('mons_class', models.CharField(choices=[('Regular', 'Regular'), ('Special', 'Special'), ('Boss', 'Boss'), ('Special_Boss', 'Special_Boss'), ('Other', 'Other')], db_column='MonsClass', max_length=32)),
                ('mons_type', models.CharField(db_column='MonsType', max_length=32)),
            ],
            options={
                'db_table': 'Monsters',
            },
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surv_img', models.ImageField(blank=True, db_column='SurvImg', null=True, upload_to='survivors/')),
                ('surv_name', models.CharField(db_column='SurvName', max_length=100)),
                ('surv_desc', models.TextField(db_column='SurvDesc')),
                ('surv_hp', models.DecimalField(db_column='SurvHP', decimal_places=2, max_digits=10)),
                ('surv_dmg', models.DecimalField(db_column='SurvDMG', decimal_places=2, max_digits=10)),
                ('surv_regen', models.DecimalField(db_column='SurvRegen', decimal_places=2, max_digits=10)),
                ('surv_armour', models.DecimalField(db_column='SurvArmour', decimal_places=2, max_digits=10)),
                ('surv_spd', models.DecimalField(db_column='SurvSpd', decimal_places=2, max_digits=10)),
                ('surv_mass', models.DecimalField(db_column='SurvMass', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'survivor',
            },
        ),
    ]
